version: "3.7"

volumes:
  mssql-data:

services:
    
        vacancies-api:
            build: .
            ports: 
                - 25010:80
            depends_on: 
                - database
            restart: always


        database:
            container_name: sql-server-db-for-vacancies-app
            image: mcr.microsoft.com/mssql/server:2019-latest
            restart: always
            volumes:
                - mssql-data:/mssql/data
            environment:
                SA_PASSWORD: "Thesecretpassword_1"
                ACCEPT_EULA: "Y"

            ports:
                - "1434:1434"